version: "3.8"

services:
  todo_db:
    image: postgres:9.4
    container_name: todo_db
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=todo_passwd_456
      - POSTGRES_USER=todo
      - POSTGRES_DB=todo
    volumes:
      - ./data_volume:/var/lib/postgresql/data:z
      - ./install.sql:/install.sql:ro
    networks:
      - todo_api
    ports:
      - 5436:5432
      
networks:
  todo_api:
    driver: bridge
